### ISSUE TITLE
core/7zip plan is Windows only

### ISSUE THREAD

**Issue by rhass** [rhass/aws_storage_gateway#1]
@mwrock It seems like adding a plan.sh for core/7zip is all that is really needed to be able to use it outside of Windows. Do you happen to know offhand if habitat can currently handle having both a `plan.ps1` and a `plan.sh`?

Thanks!

**Comment by mwrock** [comment]
currently the depot actually does not support windows plans (coming soon) so we only upload linux ones to the depot. So adding a 7-zip plan.sh and uploading it is fine.

**Comment by rhass** [comment]
Stale issue. Closing. Please reopen if needed.
